filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

output.logstash:
  enabled: true
  hosts: ["192.168.100.78:5000"]
  # FIXME: Cannot reach the hosts of Logstash

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   username: "elastic"
#   password: "changeme"
# setup.kibana:
#   host: "http://192.168.100.8:5601"
#   username: "elastic"
#   password: "changeme"